version: '3.9'

services:
  laravel-backend:
    build:
      context: ./laravel-backend
      dockerfile: Dockerfile
    container_name: adwos.cloud.backend
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: laravel-backend
      SERVICE_TAGS: dev
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    networks:
      - app-network
    volumes:
      - ./laravel-backend:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    networks:
      - app-network
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
