version: "3"
networks:
    backend:
        driver: bridge

services:
    app:
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            DB_CONNECTION: ${DB_CONNECTION}
            DB_HOST: postgres
            DB_PORT: ${DB_PORT}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_DATABASE: ${DB_DATABASE}
        env_file:
            - .env
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
        networks:
            - backend
        ports:
            - "81:81"

    redis:
        image: redis
        command: redis-server --port ${REDIS_PORT} --requirepass ${REDIS_PASSWORD}
        restart: unless-stopped
        volumes:
            - ./docker/redis/data:/data
        env_file:
            - .env
        networks:
            - backend
        ports:
            - "${REDIS_PORT}:${REDIS_PORT}"

    postgres:
        image: postgres:15
        restart: unless-stopped
        ports:
            - "5432:5432"
        volumes:
            - ./docker/postgres/data:/var/lib/postgresql/data
        networks:
            - backend
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
